print("   _______________")
print("  /               \ ")
print(" /                 \ ")
print("/                   \ ")
print("\                   /")
print(" \                 /")
print("  \               /")
print("   ---------------")